TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 5
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 5
TIME: 0	PID: 0	ACTION: SYSCALL_IN 3
TIME: 0	PID: 1	ACTION: SYSCALL_OUT 3
TIME: 0	PID: 1	ACTION: SYSCALL_IN 8
TIME: 0	PID: 1	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 1	ACTION: SYSCALL_IN 4
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 4
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 12
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 12
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 12
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 12
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 12
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 12
TIME: 0	PID: 0	ACTION: SYSCALL_IN 12
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 12
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 12
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 12
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 12
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 12
TIME: 0	PID: 0	ACTION: SYSCALL_IN 12
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 12
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 12
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 12
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 11
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 11
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 12
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 12
TIME: 0	PID: 0	ACTION: SYSCALL_IN 11
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 11
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 11
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 11
TIME: 0	PID: 0	ACTION: SYSCALL_IN 11
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 11
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 11
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 11
TIME: 0	PID: 0	ACTION: SYSCALL_IN 11
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 11
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 12
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 12
TIME: 0	PID: 0	ACTION: SYSCALL_IN 11
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 11
TIME: 0	PID: 0	ACTION: SYSCALL_IN 11
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 11
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 5
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 5
TIME: 0	PID: 0	ACTION: SYSCALL_IN 3
TIME: 0	PID: 1	ACTION: SYSCALL_OUT 3
TIME: 0	PID: 1	ACTION: SYSCALL_IN 8
TIME: 0	PID: 1	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 1	ACTION: SYSCALL_IN 4
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 4
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 5
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 5
TIME: 0	PID: 0	ACTION: SYSCALL_IN 3
TIME: 0	PID: 1	ACTION: SYSCALL_OUT 3
TIME: 0	PID: 1	ACTION: SYSCALL_IN 8
TIME: 0	PID: 1	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 1	ACTION: SYSCALL_IN 12
TIME: 0	PID: 1	ACTION: SYSCALL_OUT 12
TIME: 0	PID: 1	ACTION: SYSCALL_IN 4
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 4
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 9
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 9
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 9
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 9
TIME: 0	PID: 0	ACTION: SYSCALL_IN 9
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 9
TIME: 0	PID: 0	ACTION: SYSCALL_IN 9
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 9
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 9
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 9
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 9
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 9
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 9
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 9
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 9
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 9
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 9
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 9
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 10
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 10
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 10
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 10
TIME: 0	PID: 0	ACTION: SYSCALL_IN 10
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 10
TIME: 0	PID: 0	ACTION: SYSCALL_IN 10
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 10
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 10
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 10
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 10
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 10
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 10
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 10
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 10
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 10
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 10
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 10
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 8
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 0	PID: 0	ACTION: SYSCALL_IN 10
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 10
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: SYSCALL_IN 5
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 5
TIME: 0	PID: 0	ACTION: SYSCALL_IN 5
TIME: 0	PID: 0	ACTION: SYSCALL_OUT 5
TIME: 0	PID: 0	ACTION: SYSCALL_IN 6
TIME: 0	PID: 1	ACTION: SYSCALL_OUT 6
TIME: 0	PID: 1	ACTION: TIMER_OUT
TIME: 1	PID: 2	ACTION: TIMER_IN
TIME: 1	PID: 2	ACTION: SYSCALL_IN 8
TIME: 1	PID: 2	ACTION: SYSCALL_OUT 8
TIME: 1	PID: 2	ACTION: SYSCALL_IN 10
TIME: 1	PID: 1	ACTION: SYSCALL_OUT 10
TIME: 1	PID: 1	ACTION: TIMER_OUT
TIME: 2	PID: 1	ACTION: TIMER_IN
TIME: 2	PID: 1	ACTION: TIMER_OUT
TIME: 3	PID: 0	ACTION: TIMER_IN
TIME: 0	PID: -1	ACTION: START
TIME: 0	PID: 0	ACTION: TIMER_OUT
TIME: 1	PID: 0	ACTION: TIMER_IN
TIME: 1	PID: 0	ACTION: TIMER_OUT
TIME: 2	PID: 0	ACTION: TIMER_IN
TIME: 2	PID: 0	ACTION: TIMER_OUT
TIME: 3	PID: 0	ACTION: TIMER_IN
TIME: 3	PID: 0	ACTION: TIMER_OUT
TIME: 4	PID: 0	ACTION: TIMER_IN
TIME: 4	PID: 0	ACTION: SYSCALL_IN 5
TIME: 4	PID: 0	ACTION: SYSCALL_OUT 5
TIME: 4	PID: 0	ACTION: SYSCALL_IN 5
TIME: 4	PID: 0	ACTION: SYSCALL_OUT 5
TIME: 4	PID: 0	ACTION: SYSCALL_IN 6
TIME: 4	PID: 1	ACTION: SYSCALL_OUT 6
TIME: 4	PID: 1	ACTION: TIMER_OUT
TIME: 5	PID: 2	ACTION: TIMER_IN
TIME: 5	PID: 2	ACTION: SYSCALL_IN 8
TIME: 5	PID: 2	ACTION: SYSCALL_OUT 8
TIME: 5	PID: 2	ACTION: SYSCALL_IN 10
TIME: 5	PID: 1	ACTION: SYSCALL_OUT 10
TIME: 5	PID: 1	ACTION: TIMER_OUT
TIME: 6	PID: 1	ACTION: TIMER_IN
TIME: 6	PID: 1	ACTION: TIMER_OUT
TIME: 7	PID: 0	ACTION: TIMER_IN
TIME: 7	PID: 0	ACTION: SYSCALL_IN 8
TIME: 7	PID: 0	ACTION: SYSCALL_OUT 8
TIME: 7	PID: 0	ACTION: SYSCALL_IN 9
TIME: 7	PID: 0	ACTION: SYSCALL_OUT 9
TIME: 7	PID: 0	ACTION: SYSCALL_IN 6
TIME: 7	PID: 1	ACTION: SYSCALL_OUT 6
TIME: 7	PID: 1	ACTION: TIMER_OUT
TIME: 8	PID: 2	ACTION: TIMER_IN
TIME: 8	PID: 2	ACTION: SYSCALL_IN 10
TIME: 8	PID: 2	ACTION: SYSCALL_OUT 10
TIME: 8	PID: 2	ACTION: SYSCALL_IN 4
TIME: 8	PID: 1	ACTION: SYSCALL_OUT 4
TIME: 8	PID: 1	ACTION: TIMER_OUT
TIME: 9	PID: 1	ACTION: TIMER_IN
TIME: 9	PID: 1	ACTION: TIMER_OUT
TIME: 10	PID: 0	ACTION: TIMER_IN
TIME: 10	PID: 0	ACTION: SYSCALL_IN 3
TIME: 10	PID: 0	ACTION: SYSCALL_OUT 3
